//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LF_XML_To_Excel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LFSize
    {
        public int uid { get; set; }
        public string Cus_id { get; set; }
        public string EDISize { get; set; }
        public string ERPSize { get; set; }
        public Nullable<System.DateTime> 建立日期 { get; set; }
    }
}
